services:
  db:
    image: mysql
    container_name: mysql_gatito
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: gatito_petshop
    ports:
      - 3306:3306
      - 33060:33060
  adminer:
    image: adminer
    container_name: adminer_gatito
    restart: always
    ports:
      - 8080:8080
